openapi: 3.0.0
info:
  title: HRIS API
  version: "1.0"
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /profile/{id}:
    get:
      summary: Get employee profile by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Employee data or not found message
          content:
            application/json:
              schema:
                type: object
    patch:
      summary: Update employee profile by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        description: Fields to update in employee record
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated employee data or error message
          content:
            application/json:
              schema:
                type: object
  /leave/apply:
    post:
      summary: Apply for leave
      requestBody:
        description: Details of the leave request
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employee_id:
                  type: integer
                leave_type:
                  type: string
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
      responses:
        '200':
          description: Leave request data or error message
          content:
            application/json:
              schema:
                type: object
  /internal-application:
    post:
      summary: Apply for internal job
      requestBody:
        description: Application details for an internal job
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employee_id:
                  type: integer
                apply_for_position:
                  type: string
      responses:
        '201':
          description: Application submitted successfully along with application data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
